[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22.16.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_TOKEN = ""
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "true"
  NPM_CONFIG_PACKAGE_LOCK = "true"
  NPM_CONFIG_USE_PNPM = "false"
  NPM_CONFIG_USE_YARN = "false"
  NPM_CONFIG_USE_NPM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-npm"

[functions]
  node_bundler = "esbuild" 