[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22.16.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_TOKEN = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 